### ISSUE TITLE
'model-create' is not a valid view function or pattern name

### ISSUE THREAD

**Issue by tantalusblank** [carltongibson/neapolitan#51] opened 2024-07-05 17:38 UTC
I'm currently trying to implement Neapolitan into my Django project for the first time and getting the error as per the title.

### First Some Detail
- Wanting to add views for an additional model in an app that already has working manually added CRUD views for other models  
- Using Neapolitan==24.4
- Added to INSTALLED_APPS
- Trying to use on the following model:
```
class Asset(models.Model):
    """Models a specific asset."""
    asset_type = models.ForeignKey(AssetType, on_delete=models.CASCADE)
    asset_number = models.CharField(max_length=20)
```
- Using a CRUDview:
```
from neapolitan.views import CRUDView
from models import Asset

class AssetView(CRUDView):
    model = Asset
    fields = ["asset_type", "asset_number"]
```
- And added in to `urls.py`:
```
urlpatterns += views.AssetView.get_urls()
```
### The Problem
Unfortunately when I do this and try to navigate to `http://127.0.0.1:8000/engineeringinterface/asset/`, I get the following:

```
Request URL: http://127.0.0.1:8000/engineeringinterface/asset/
Django Version: 5.0.6
Exception Type: NoReverseMatch
Exception Value: Reverse for 'asset-create' not found. 'asset-create' is not a valid view function or pattern name.
```

I'm relatively new to Django, so there may be some convention I'm not following properly.

### Suspect Causes

1. The folder structure could be unconventional, and maybe I need to specifically define a path somewhere
Current structure is:
```
project_root
|_ manage.py
|_ src
   |_ my_app
      |_ settings.py
      |_ urls.py
      |_ engineeringinterface
         |_ models.py
         |_ views.py
         |_ urls.py
         |_ templates
            |_ engineeringinterface
               |_ base.html
```
(some files and folders omitted, but mainly to show ones of significance)

2. Another installed app or middleware causing an issue (e.g. django-simple-history)

**Comment by carltongibson** [comment] 2024-07-05 18:02
@tantalusblank That looks OK. Can you give me a running example?

**Comment by tantalusblank** [comment] 2024-07-05 19:05
Thanks for the speedy reply @carltongibson, though sorry could you clarify what you mean by a running example?

**Comment by carltongibson** [comment] 2024-07-05 19:48
Like a test case or example project that shows the issue. (There's something you didn't tell me, but I don't know what.)

**Comment by carltongibson** [comment] 2024-07-06 12:01
@tantalusblank Give v24.5 a go, which I just released, that fixes a maybe related issue. 

If that doesn't solve it then you'll need to give me an example project to look at.

**Comment by tantalusblank** [comment] 2024-07-06 13:21
Thanks I'll give 24.5 a go on Monday - really appreciate the support. If that doesn't work I'll try and share as much of the project as possible

**Comment by carltongibson** [comment] 2024-07-06 13:23
Great. Thanks. 

I'd suggest starting with a fresh project , then try to reproduce the issue with the absolute minimum you need to add. That will show exactly where the issue is.

**Comment by tantalusblank** [comment] 2024-07-08 13:35
While 24.5 did seem to solve the problem I was having, it then couldn't find base.html (until I duplicated it into the templates root), and now it is displaying the table! However, although it could be a CSS issue, I can't see any options to create/modify/delete any records.

You should have an invite to a project that is a stripped down version of the app.

**Comment by carltongibson** [comment] 2024-07-08 14:26
`app_name = "engineeringinterface"`

Neapolitan's view name generation is not compatible with url namespaces. Either don't use one, or move your CRUDView URLs into your main URLConf.

**Comment by carltongibson** [comment] 2024-07-08 14:33
Duplicate of #16 really

**Closed** 2024-07-08 14:34 UTC
Labels: documentation

**Comment by tantalusblank** [comment] 2024-07-08 15:54
Removed the namespace and everything seems to work fine - thanks @carltongibson

**Comment by carltongibson** [comment] 2024-07-08 17:33
Great. Thanks for the follow up!
